services:
  api:
    image: ghcr.io/gabrielhamel/ddd-lab/api:main
    ports:
      - "127.0.0.1:15080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    restart: "always"

  ui:
    image: ghcr.io/gabrielhamel/ddd-lab/ui:main
    ports:
      - "127.0.0.1:15081:80"
    restart: "always"

  grafana:
    image: grafana/grafana
    ports:
      - "127.0.0.1:15082:3000"
    environment:
      - GF_SECURITY_ADMIN_USER="${GF_SECURITY_ADMIN_USER}"
      - GF_SECURITY_ADMIN_PASSWORD="${GF_SECURITY_ADMIN_PASSWORD}"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-conf:/etc/grafana
    restart: "always"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  grafana-data:
  grafana-conf:
