/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventStormingIndexRouteImport } from './routes/event-storming/index'
import { Route as EventStormingEventStormingIdRouteImport } from './routes/event-storming/$eventStormingId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventStormingIndexRoute = EventStormingIndexRouteImport.update({
  id: '/event-storming/',
  path: '/event-storming/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventStormingEventStormingIdRoute =
  EventStormingEventStormingIdRouteImport.update({
    id: '/event-storming/$eventStormingId',
    path: '/event-storming/$eventStormingId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/event-storming/$eventStormingId': typeof EventStormingEventStormingIdRoute
  '/event-storming/': typeof EventStormingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/event-storming/$eventStormingId': typeof EventStormingEventStormingIdRoute
  '/event-storming': typeof EventStormingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/event-storming/$eventStormingId': typeof EventStormingEventStormingIdRoute
  '/event-storming/': typeof EventStormingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/event-storming/$eventStormingId'
    | '/event-storming/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/event-storming/$eventStormingId' | '/event-storming'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/event-storming/$eventStormingId'
    | '/event-storming/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EventStormingEventStormingIdRoute: typeof EventStormingEventStormingIdRoute
  EventStormingIndexRoute: typeof EventStormingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-storming/': {
      id: '/event-storming/'
      path: '/event-storming'
      fullPath: '/event-storming/'
      preLoaderRoute: typeof EventStormingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-storming/$eventStormingId': {
      id: '/event-storming/$eventStormingId'
      path: '/event-storming/$eventStormingId'
      fullPath: '/event-storming/$eventStormingId'
      preLoaderRoute: typeof EventStormingEventStormingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EventStormingEventStormingIdRoute: EventStormingEventStormingIdRoute,
  EventStormingIndexRoute: EventStormingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
