# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    assignees:
      - "gabrielhamel"
    schedule:
      interval: "weekly"
    groups:
      emotion-major:
        update-types:
          - "major"
        patterns:
          - "@emotion/*"

      hocuspocus-major:
        update-types:
          - "major"
        patterns:
          - "@hocuspocus/*"

      mui-major:
        update-types:
          - "major"
        patterns:
          - "@mui/*"

      orpc-major:
        update-types:
          - "major"
        patterns:
          - "@orpc/*"

      prisma-major:
        update-types:
          - "major"
        patterns:
          - "@prisma/*"
          - "prisma"

      tanstack-query-major:
        update-types:
          - "major"
        patterns:
          - "@tanstack/eslint-plugin-query"
          - "@tanstack/react-query"

      tanstack-router-major:
        update-types:
          - "major"
        patterns:
          - "@tanstack/eslint-plugin-router"
          - "@tanstack/react-router"
          - "@tanstack/router-plugin"

      react-major:
        update-types:
          - "major"
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"

      better-auth-major:
        update-types:
          - "major"
        patterns:
          - "auth"
          - "better-auth"

      vite-plus-major:
        update-types:
          - "major"
        patterns:
          - "vite"
          - "vite-plus"
          - "vitest"

      non-breaking:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
