services:
  api:
    image: ghcr.io/gabrielhamel/ddd-lab/event-storming/api:main
    ports:
      - "127.0.0.1:15080:8080"
    restart: "always"

  ui:
    image: ghcr.io/gabrielhamel/ddd-lab/event-storming/ui:main
    ports:
      - "127.0.0.1:15081:80"
    restart: "always"
