services:
  api:
    build:
      context: .
      dockerfile: event-storming/api/Dockerfile
    image: event-storming-api:latest
    ports:
      - "127.0.0.1:15080:8080"

  ui:
    build:
      context: .
      dockerfile: event-storming/ui/Dockerfile
      args:
        - VITE_API_WS_URL=ws://localhost:15080/api/event-storming/collaboration
    image: event-storming-ui:latest
    ports:
      - "127.0.0.1:15081:80"
