/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `EventStorming` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums";
import type * as Prisma from "../internal/prismaNamespace";

/**
 * Model EventStorming
 *
 */
export type EventStormingModel =
  runtime.Types.Result.DefaultSelection<Prisma.$EventStormingPayload>;

export type AggregateEventStorming = {
  _count: EventStormingCountAggregateOutputType | null;
  _min: EventStormingMinAggregateOutputType | null;
  _max: EventStormingMaxAggregateOutputType | null;
};

export type EventStormingMinAggregateOutputType = {
  id: string | null;
  name: string | null;
  data: runtime.Bytes | null;
  ownerId: string | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type EventStormingMaxAggregateOutputType = {
  id: string | null;
  name: string | null;
  data: runtime.Bytes | null;
  ownerId: string | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type EventStormingCountAggregateOutputType = {
  id: number;
  name: number;
  data: number;
  ownerId: number;
  createdAt: number;
  updatedAt: number;
  _all: number;
};

export type EventStormingMinAggregateInputType = {
  id?: true;
  name?: true;
  data?: true;
  ownerId?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type EventStormingMaxAggregateInputType = {
  id?: true;
  name?: true;
  data?: true;
  ownerId?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type EventStormingCountAggregateInputType = {
  id?: true;
  name?: true;
  data?: true;
  ownerId?: true;
  createdAt?: true;
  updatedAt?: true;
  _all?: true;
};

export type EventStormingAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which EventStorming to aggregate.
   */
  where?: Prisma.EventStormingWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of EventStormings to fetch.
   */
  orderBy?:
    | Prisma.EventStormingOrderByWithRelationInput
    | Prisma.EventStormingOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.EventStormingWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` EventStormings from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` EventStormings.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned EventStormings
   **/
  _count?: true | EventStormingCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: EventStormingMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: EventStormingMaxAggregateInputType;
};

export type GetEventStormingAggregateType<T extends EventStormingAggregateArgs> = {
  [P in keyof T & keyof AggregateEventStorming]: P extends "_count" | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEventStorming[P]>
    : Prisma.GetScalarType<T[P], AggregateEventStorming[P]>;
};

export type EventStormingGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.EventStormingWhereInput;
  orderBy?:
    | Prisma.EventStormingOrderByWithAggregationInput
    | Prisma.EventStormingOrderByWithAggregationInput[];
  by: Prisma.EventStormingScalarFieldEnum[] | Prisma.EventStormingScalarFieldEnum;
  having?: Prisma.EventStormingScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: EventStormingCountAggregateInputType | true;
  _min?: EventStormingMinAggregateInputType;
  _max?: EventStormingMaxAggregateInputType;
};

export type EventStormingGroupByOutputType = {
  id: string;
  name: string;
  data: runtime.Bytes | null;
  ownerId: string;
  createdAt: Date;
  updatedAt: Date;
  _count: EventStormingCountAggregateOutputType | null;
  _min: EventStormingMinAggregateOutputType | null;
  _max: EventStormingMaxAggregateOutputType | null;
};

export type GetEventStormingGroupByPayload<T extends EventStormingGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<EventStormingGroupByOutputType, T["by"]> & {
        [P in keyof T & keyof EventStormingGroupByOutputType]: P extends "_count"
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EventStormingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EventStormingGroupByOutputType[P]>;
      }
    >
  >;

export type EventStormingWhereInput = {
  AND?: Prisma.EventStormingWhereInput | Prisma.EventStormingWhereInput[];
  OR?: Prisma.EventStormingWhereInput[];
  NOT?: Prisma.EventStormingWhereInput | Prisma.EventStormingWhereInput[];
  id?: Prisma.StringFilter<"EventStorming"> | string;
  name?: Prisma.StringFilter<"EventStorming"> | string;
  data?: Prisma.BytesNullableFilter<"EventStorming"> | runtime.Bytes | null;
  ownerId?: Prisma.StringFilter<"EventStorming"> | string;
  createdAt?: Prisma.DateTimeFilter<"EventStorming"> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<"EventStorming"> | Date | string;
  owner?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
};

export type EventStormingOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  data?: Prisma.SortOrderInput | Prisma.SortOrder;
  ownerId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  owner?: Prisma.UserOrderByWithRelationInput;
};

export type EventStormingWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    AND?: Prisma.EventStormingWhereInput | Prisma.EventStormingWhereInput[];
    OR?: Prisma.EventStormingWhereInput[];
    NOT?: Prisma.EventStormingWhereInput | Prisma.EventStormingWhereInput[];
    name?: Prisma.StringFilter<"EventStorming"> | string;
    data?: Prisma.BytesNullableFilter<"EventStorming"> | runtime.Bytes | null;
    ownerId?: Prisma.StringFilter<"EventStorming"> | string;
    createdAt?: Prisma.DateTimeFilter<"EventStorming"> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<"EventStorming"> | Date | string;
    owner?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
  },
  "id"
>;

export type EventStormingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  data?: Prisma.SortOrderInput | Prisma.SortOrder;
  ownerId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  _count?: Prisma.EventStormingCountOrderByAggregateInput;
  _max?: Prisma.EventStormingMaxOrderByAggregateInput;
  _min?: Prisma.EventStormingMinOrderByAggregateInput;
};

export type EventStormingScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.EventStormingScalarWhereWithAggregatesInput
    | Prisma.EventStormingScalarWhereWithAggregatesInput[];
  OR?: Prisma.EventStormingScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.EventStormingScalarWhereWithAggregatesInput
    | Prisma.EventStormingScalarWhereWithAggregatesInput[];
  id?: Prisma.StringWithAggregatesFilter<"EventStorming"> | string;
  name?: Prisma.StringWithAggregatesFilter<"EventStorming"> | string;
  data?: Prisma.BytesNullableWithAggregatesFilter<"EventStorming"> | runtime.Bytes | null;
  ownerId?: Prisma.StringWithAggregatesFilter<"EventStorming"> | string;
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EventStorming"> | Date | string;
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"EventStorming"> | Date | string;
};

export type EventStormingCreateInput = {
  id: string;
  name: string;
  data?: runtime.Bytes | null;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  owner: Prisma.UserCreateNestedOneWithoutEventStormingsInput;
};

export type EventStormingUncheckedCreateInput = {
  id: string;
  name: string;
  data?: runtime.Bytes | null;
  ownerId: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type EventStormingUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  data?: Prisma.NullableBytesFieldUpdateOperationsInput | runtime.Bytes | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  owner?: Prisma.UserUpdateOneRequiredWithoutEventStormingsNestedInput;
};

export type EventStormingUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  data?: Prisma.NullableBytesFieldUpdateOperationsInput | runtime.Bytes | null;
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type EventStormingCreateManyInput = {
  id: string;
  name: string;
  data?: runtime.Bytes | null;
  ownerId: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type EventStormingUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  data?: Prisma.NullableBytesFieldUpdateOperationsInput | runtime.Bytes | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type EventStormingUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  data?: Prisma.NullableBytesFieldUpdateOperationsInput | runtime.Bytes | null;
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type EventStormingListRelationFilter = {
  every?: Prisma.EventStormingWhereInput;
  some?: Prisma.EventStormingWhereInput;
  none?: Prisma.EventStormingWhereInput;
};

export type EventStormingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type EventStormingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  data?: Prisma.SortOrder;
  ownerId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type EventStormingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  data?: Prisma.SortOrder;
  ownerId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type EventStormingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  data?: Prisma.SortOrder;
  ownerId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type EventStormingCreateNestedManyWithoutOwnerInput = {
  create?:
    | Prisma.XOR<
        Prisma.EventStormingCreateWithoutOwnerInput,
        Prisma.EventStormingUncheckedCreateWithoutOwnerInput
      >
    | Prisma.EventStormingCreateWithoutOwnerInput[]
    | Prisma.EventStormingUncheckedCreateWithoutOwnerInput[];
  connectOrCreate?:
    | Prisma.EventStormingCreateOrConnectWithoutOwnerInput
    | Prisma.EventStormingCreateOrConnectWithoutOwnerInput[];
  createMany?: Prisma.EventStormingCreateManyOwnerInputEnvelope;
  connect?: Prisma.EventStormingWhereUniqueInput | Prisma.EventStormingWhereUniqueInput[];
};

export type EventStormingUncheckedCreateNestedManyWithoutOwnerInput = {
  create?:
    | Prisma.XOR<
        Prisma.EventStormingCreateWithoutOwnerInput,
        Prisma.EventStormingUncheckedCreateWithoutOwnerInput
      >
    | Prisma.EventStormingCreateWithoutOwnerInput[]
    | Prisma.EventStormingUncheckedCreateWithoutOwnerInput[];
  connectOrCreate?:
    | Prisma.EventStormingCreateOrConnectWithoutOwnerInput
    | Prisma.EventStormingCreateOrConnectWithoutOwnerInput[];
  createMany?: Prisma.EventStormingCreateManyOwnerInputEnvelope;
  connect?: Prisma.EventStormingWhereUniqueInput | Prisma.EventStormingWhereUniqueInput[];
};

export type EventStormingUpdateManyWithoutOwnerNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.EventStormingCreateWithoutOwnerInput,
        Prisma.EventStormingUncheckedCreateWithoutOwnerInput
      >
    | Prisma.EventStormingCreateWithoutOwnerInput[]
    | Prisma.EventStormingUncheckedCreateWithoutOwnerInput[];
  connectOrCreate?:
    | Prisma.EventStormingCreateOrConnectWithoutOwnerInput
    | Prisma.EventStormingCreateOrConnectWithoutOwnerInput[];
  upsert?:
    | Prisma.EventStormingUpsertWithWhereUniqueWithoutOwnerInput
    | Prisma.EventStormingUpsertWithWhereUniqueWithoutOwnerInput[];
  createMany?: Prisma.EventStormingCreateManyOwnerInputEnvelope;
  set?: Prisma.EventStormingWhereUniqueInput | Prisma.EventStormingWhereUniqueInput[];
  disconnect?: Prisma.EventStormingWhereUniqueInput | Prisma.EventStormingWhereUniqueInput[];
  delete?: Prisma.EventStormingWhereUniqueInput | Prisma.EventStormingWhereUniqueInput[];
  connect?: Prisma.EventStormingWhereUniqueInput | Prisma.EventStormingWhereUniqueInput[];
  update?:
    | Prisma.EventStormingUpdateWithWhereUniqueWithoutOwnerInput
    | Prisma.EventStormingUpdateWithWhereUniqueWithoutOwnerInput[];
  updateMany?:
    | Prisma.EventStormingUpdateManyWithWhereWithoutOwnerInput
    | Prisma.EventStormingUpdateManyWithWhereWithoutOwnerInput[];
  deleteMany?: Prisma.EventStormingScalarWhereInput | Prisma.EventStormingScalarWhereInput[];
};

export type EventStormingUncheckedUpdateManyWithoutOwnerNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.EventStormingCreateWithoutOwnerInput,
        Prisma.EventStormingUncheckedCreateWithoutOwnerInput
      >
    | Prisma.EventStormingCreateWithoutOwnerInput[]
    | Prisma.EventStormingUncheckedCreateWithoutOwnerInput[];
  connectOrCreate?:
    | Prisma.EventStormingCreateOrConnectWithoutOwnerInput
    | Prisma.EventStormingCreateOrConnectWithoutOwnerInput[];
  upsert?:
    | Prisma.EventStormingUpsertWithWhereUniqueWithoutOwnerInput
    | Prisma.EventStormingUpsertWithWhereUniqueWithoutOwnerInput[];
  createMany?: Prisma.EventStormingCreateManyOwnerInputEnvelope;
  set?: Prisma.EventStormingWhereUniqueInput | Prisma.EventStormingWhereUniqueInput[];
  disconnect?: Prisma.EventStormingWhereUniqueInput | Prisma.EventStormingWhereUniqueInput[];
  delete?: Prisma.EventStormingWhereUniqueInput | Prisma.EventStormingWhereUniqueInput[];
  connect?: Prisma.EventStormingWhereUniqueInput | Prisma.EventStormingWhereUniqueInput[];
  update?:
    | Prisma.EventStormingUpdateWithWhereUniqueWithoutOwnerInput
    | Prisma.EventStormingUpdateWithWhereUniqueWithoutOwnerInput[];
  updateMany?:
    | Prisma.EventStormingUpdateManyWithWhereWithoutOwnerInput
    | Prisma.EventStormingUpdateManyWithWhereWithoutOwnerInput[];
  deleteMany?: Prisma.EventStormingScalarWhereInput | Prisma.EventStormingScalarWhereInput[];
};

export type NullableBytesFieldUpdateOperationsInput = {
  set?: runtime.Bytes | null;
};

export type EventStormingCreateWithoutOwnerInput = {
  id: string;
  name: string;
  data?: runtime.Bytes | null;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type EventStormingUncheckedCreateWithoutOwnerInput = {
  id: string;
  name: string;
  data?: runtime.Bytes | null;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type EventStormingCreateOrConnectWithoutOwnerInput = {
  where: Prisma.EventStormingWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.EventStormingCreateWithoutOwnerInput,
    Prisma.EventStormingUncheckedCreateWithoutOwnerInput
  >;
};

export type EventStormingCreateManyOwnerInputEnvelope = {
  data: Prisma.EventStormingCreateManyOwnerInput | Prisma.EventStormingCreateManyOwnerInput[];
  skipDuplicates?: boolean;
};

export type EventStormingUpsertWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.EventStormingWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.EventStormingUpdateWithoutOwnerInput,
    Prisma.EventStormingUncheckedUpdateWithoutOwnerInput
  >;
  create: Prisma.XOR<
    Prisma.EventStormingCreateWithoutOwnerInput,
    Prisma.EventStormingUncheckedCreateWithoutOwnerInput
  >;
};

export type EventStormingUpdateWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.EventStormingWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.EventStormingUpdateWithoutOwnerInput,
    Prisma.EventStormingUncheckedUpdateWithoutOwnerInput
  >;
};

export type EventStormingUpdateManyWithWhereWithoutOwnerInput = {
  where: Prisma.EventStormingScalarWhereInput;
  data: Prisma.XOR<
    Prisma.EventStormingUpdateManyMutationInput,
    Prisma.EventStormingUncheckedUpdateManyWithoutOwnerInput
  >;
};

export type EventStormingScalarWhereInput = {
  AND?: Prisma.EventStormingScalarWhereInput | Prisma.EventStormingScalarWhereInput[];
  OR?: Prisma.EventStormingScalarWhereInput[];
  NOT?: Prisma.EventStormingScalarWhereInput | Prisma.EventStormingScalarWhereInput[];
  id?: Prisma.StringFilter<"EventStorming"> | string;
  name?: Prisma.StringFilter<"EventStorming"> | string;
  data?: Prisma.BytesNullableFilter<"EventStorming"> | runtime.Bytes | null;
  ownerId?: Prisma.StringFilter<"EventStorming"> | string;
  createdAt?: Prisma.DateTimeFilter<"EventStorming"> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<"EventStorming"> | Date | string;
};

export type EventStormingCreateManyOwnerInput = {
  id: string;
  name: string;
  data?: runtime.Bytes | null;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type EventStormingUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  data?: Prisma.NullableBytesFieldUpdateOperationsInput | runtime.Bytes | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type EventStormingUncheckedUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  data?: Prisma.NullableBytesFieldUpdateOperationsInput | runtime.Bytes | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type EventStormingUncheckedUpdateManyWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  data?: Prisma.NullableBytesFieldUpdateOperationsInput | runtime.Bytes | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type EventStormingSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    name?: boolean;
    data?: boolean;
    ownerId?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["eventStorming"]
>;

export type EventStormingSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    name?: boolean;
    data?: boolean;
    ownerId?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["eventStorming"]
>;

export type EventStormingSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    name?: boolean;
    data?: boolean;
    ownerId?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["eventStorming"]
>;

export type EventStormingSelectScalar = {
  id?: boolean;
  name?: boolean;
  data?: boolean;
  ownerId?: boolean;
  createdAt?: boolean;
  updatedAt?: boolean;
};

export type EventStormingOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  "id" | "name" | "data" | "ownerId" | "createdAt" | "updatedAt",
  ExtArgs["result"]["eventStorming"]
>;
export type EventStormingInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};
export type EventStormingIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};
export type EventStormingIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};

export type $EventStormingPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: "EventStorming";
  objects: {
    owner: Prisma.$UserPayload<ExtArgs>;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      name: string;
      data: runtime.Bytes | null;
      ownerId: string;
      createdAt: Date;
      updatedAt: Date;
    },
    ExtArgs["result"]["eventStorming"]
  >;
  composites: {};
};

export type EventStormingGetPayload<
  S extends boolean | null | undefined | EventStormingDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$EventStormingPayload, S>;

export type EventStormingCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<EventStormingFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
  select?: EventStormingCountAggregateInputType | true;
};

export interface EventStormingDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["EventStorming"];
    meta: { name: "EventStorming" };
  };
  /**
   * Find zero or one EventStorming that matches the filter.
   * @param {EventStormingFindUniqueArgs} args - Arguments to find a EventStorming
   * @example
   * // Get one EventStorming
   * const eventStorming = await prisma.eventStorming.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EventStormingFindUniqueArgs>(
    args: Prisma.SelectSubset<T, EventStormingFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__EventStormingClient<
    runtime.Types.Result.GetResult<
      Prisma.$EventStormingPayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one EventStorming that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EventStormingFindUniqueOrThrowArgs} args - Arguments to find a EventStorming
   * @example
   * // Get one EventStorming
   * const eventStorming = await prisma.eventStorming.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EventStormingFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, EventStormingFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__EventStormingClient<
    runtime.Types.Result.GetResult<
      Prisma.$EventStormingPayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first EventStorming that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventStormingFindFirstArgs} args - Arguments to find a EventStorming
   * @example
   * // Get one EventStorming
   * const eventStorming = await prisma.eventStorming.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EventStormingFindFirstArgs>(
    args?: Prisma.SelectSubset<T, EventStormingFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__EventStormingClient<
    runtime.Types.Result.GetResult<
      Prisma.$EventStormingPayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first EventStorming that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventStormingFindFirstOrThrowArgs} args - Arguments to find a EventStorming
   * @example
   * // Get one EventStorming
   * const eventStorming = await prisma.eventStorming.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EventStormingFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, EventStormingFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__EventStormingClient<
    runtime.Types.Result.GetResult<
      Prisma.$EventStormingPayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more EventStormings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventStormingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EventStormings
   * const eventStormings = await prisma.eventStorming.findMany()
   *
   * // Get first 10 EventStormings
   * const eventStormings = await prisma.eventStorming.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const eventStormingWithIdOnly = await prisma.eventStorming.findMany({ select: { id: true } })
   *
   */
  findMany<T extends EventStormingFindManyArgs>(
    args?: Prisma.SelectSubset<T, EventStormingFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$EventStormingPayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >;

  /**
   * Create a EventStorming.
   * @param {EventStormingCreateArgs} args - Arguments to create a EventStorming.
   * @example
   * // Create one EventStorming
   * const EventStorming = await prisma.eventStorming.create({
   *   data: {
   *     // ... data to create a EventStorming
   *   }
   * })
   *
   */
  create<T extends EventStormingCreateArgs>(
    args: Prisma.SelectSubset<T, EventStormingCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__EventStormingClient<
    runtime.Types.Result.GetResult<
      Prisma.$EventStormingPayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many EventStormings.
   * @param {EventStormingCreateManyArgs} args - Arguments to create many EventStormings.
   * @example
   * // Create many EventStormings
   * const eventStorming = await prisma.eventStorming.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends EventStormingCreateManyArgs>(
    args?: Prisma.SelectSubset<T, EventStormingCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many EventStormings and returns the data saved in the database.
   * @param {EventStormingCreateManyAndReturnArgs} args - Arguments to create many EventStormings.
   * @example
   * // Create many EventStormings
   * const eventStorming = await prisma.eventStorming.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many EventStormings and only return the `id`
   * const eventStormingWithIdOnly = await prisma.eventStorming.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends EventStormingCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, EventStormingCreateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$EventStormingPayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a EventStorming.
   * @param {EventStormingDeleteArgs} args - Arguments to delete one EventStorming.
   * @example
   * // Delete one EventStorming
   * const EventStorming = await prisma.eventStorming.delete({
   *   where: {
   *     // ... filter to delete one EventStorming
   *   }
   * })
   *
   */
  delete<T extends EventStormingDeleteArgs>(
    args: Prisma.SelectSubset<T, EventStormingDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__EventStormingClient<
    runtime.Types.Result.GetResult<
      Prisma.$EventStormingPayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one EventStorming.
   * @param {EventStormingUpdateArgs} args - Arguments to update one EventStorming.
   * @example
   * // Update one EventStorming
   * const eventStorming = await prisma.eventStorming.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends EventStormingUpdateArgs>(
    args: Prisma.SelectSubset<T, EventStormingUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__EventStormingClient<
    runtime.Types.Result.GetResult<
      Prisma.$EventStormingPayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more EventStormings.
   * @param {EventStormingDeleteManyArgs} args - Arguments to filter EventStormings to delete.
   * @example
   * // Delete a few EventStormings
   * const { count } = await prisma.eventStorming.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends EventStormingDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, EventStormingDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more EventStormings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventStormingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EventStormings
   * const eventStorming = await prisma.eventStorming.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends EventStormingUpdateManyArgs>(
    args: Prisma.SelectSubset<T, EventStormingUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more EventStormings and returns the data updated in the database.
   * @param {EventStormingUpdateManyAndReturnArgs} args - Arguments to update many EventStormings.
   * @example
   * // Update many EventStormings
   * const eventStorming = await prisma.eventStorming.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more EventStormings and only return the `id`
   * const eventStormingWithIdOnly = await prisma.eventStorming.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends EventStormingUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, EventStormingUpdateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$EventStormingPayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one EventStorming.
   * @param {EventStormingUpsertArgs} args - Arguments to update or create a EventStorming.
   * @example
   * // Update or create a EventStorming
   * const eventStorming = await prisma.eventStorming.upsert({
   *   create: {
   *     // ... data to create a EventStorming
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EventStorming we want to update
   *   }
   * })
   */
  upsert<T extends EventStormingUpsertArgs>(
    args: Prisma.SelectSubset<T, EventStormingUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__EventStormingClient<
    runtime.Types.Result.GetResult<
      Prisma.$EventStormingPayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of EventStormings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventStormingCountArgs} args - Arguments to filter EventStormings to count.
   * @example
   * // Count the number of EventStormings
   * const count = await prisma.eventStorming.count({
   *   where: {
   *     // ... the filter for the EventStormings we want to count
   *   }
   * })
   **/
  count<T extends EventStormingCountArgs>(
    args?: Prisma.Subset<T, EventStormingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<T["select"], EventStormingCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a EventStorming.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventStormingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends EventStormingAggregateArgs>(
    args: Prisma.Subset<T, EventStormingAggregateArgs>,
  ): Prisma.PrismaPromise<GetEventStormingAggregateType<T>>;

  /**
   * Group by EventStorming.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventStormingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends EventStormingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EventStormingGroupByArgs["orderBy"] }
      : { orderBy?: EventStormingGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, EventStormingGroupByArgs, OrderByArg> & InputErrors,
  ): {} extends InputErrors ? GetEventStormingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the EventStorming model
   */
  readonly fields: EventStormingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EventStorming.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EventStormingClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise";
  owner<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__UserClient<
    | runtime.Types.Result.GetResult<
        Prisma.$UserPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the EventStorming model
 */
export interface EventStormingFieldRefs {
  readonly id: Prisma.FieldRef<"EventStorming", "String">;
  readonly name: Prisma.FieldRef<"EventStorming", "String">;
  readonly data: Prisma.FieldRef<"EventStorming", "Bytes">;
  readonly ownerId: Prisma.FieldRef<"EventStorming", "String">;
  readonly createdAt: Prisma.FieldRef<"EventStorming", "DateTime">;
  readonly updatedAt: Prisma.FieldRef<"EventStorming", "DateTime">;
}

// Custom InputTypes
/**
 * EventStorming findUnique
 */
export type EventStormingFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the EventStorming
   */
  select?: Prisma.EventStormingSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the EventStorming
   */
  omit?: Prisma.EventStormingOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventStormingInclude<ExtArgs> | null;
  /**
   * Filter, which EventStorming to fetch.
   */
  where: Prisma.EventStormingWhereUniqueInput;
};

/**
 * EventStorming findUniqueOrThrow
 */
export type EventStormingFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the EventStorming
   */
  select?: Prisma.EventStormingSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the EventStorming
   */
  omit?: Prisma.EventStormingOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventStormingInclude<ExtArgs> | null;
  /**
   * Filter, which EventStorming to fetch.
   */
  where: Prisma.EventStormingWhereUniqueInput;
};

/**
 * EventStorming findFirst
 */
export type EventStormingFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the EventStorming
   */
  select?: Prisma.EventStormingSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the EventStorming
   */
  omit?: Prisma.EventStormingOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventStormingInclude<ExtArgs> | null;
  /**
   * Filter, which EventStorming to fetch.
   */
  where?: Prisma.EventStormingWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of EventStormings to fetch.
   */
  orderBy?:
    | Prisma.EventStormingOrderByWithRelationInput
    | Prisma.EventStormingOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for EventStormings.
   */
  cursor?: Prisma.EventStormingWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` EventStormings from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` EventStormings.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of EventStormings.
   */
  distinct?: Prisma.EventStormingScalarFieldEnum | Prisma.EventStormingScalarFieldEnum[];
};

/**
 * EventStorming findFirstOrThrow
 */
export type EventStormingFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the EventStorming
   */
  select?: Prisma.EventStormingSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the EventStorming
   */
  omit?: Prisma.EventStormingOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventStormingInclude<ExtArgs> | null;
  /**
   * Filter, which EventStorming to fetch.
   */
  where?: Prisma.EventStormingWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of EventStormings to fetch.
   */
  orderBy?:
    | Prisma.EventStormingOrderByWithRelationInput
    | Prisma.EventStormingOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for EventStormings.
   */
  cursor?: Prisma.EventStormingWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` EventStormings from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` EventStormings.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of EventStormings.
   */
  distinct?: Prisma.EventStormingScalarFieldEnum | Prisma.EventStormingScalarFieldEnum[];
};

/**
 * EventStorming findMany
 */
export type EventStormingFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the EventStorming
   */
  select?: Prisma.EventStormingSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the EventStorming
   */
  omit?: Prisma.EventStormingOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventStormingInclude<ExtArgs> | null;
  /**
   * Filter, which EventStormings to fetch.
   */
  where?: Prisma.EventStormingWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of EventStormings to fetch.
   */
  orderBy?:
    | Prisma.EventStormingOrderByWithRelationInput
    | Prisma.EventStormingOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing EventStormings.
   */
  cursor?: Prisma.EventStormingWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` EventStormings from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` EventStormings.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of EventStormings.
   */
  distinct?: Prisma.EventStormingScalarFieldEnum | Prisma.EventStormingScalarFieldEnum[];
};

/**
 * EventStorming create
 */
export type EventStormingCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the EventStorming
   */
  select?: Prisma.EventStormingSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the EventStorming
   */
  omit?: Prisma.EventStormingOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventStormingInclude<ExtArgs> | null;
  /**
   * The data needed to create a EventStorming.
   */
  data: Prisma.XOR<Prisma.EventStormingCreateInput, Prisma.EventStormingUncheckedCreateInput>;
};

/**
 * EventStorming createMany
 */
export type EventStormingCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many EventStormings.
   */
  data: Prisma.EventStormingCreateManyInput | Prisma.EventStormingCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * EventStorming createManyAndReturn
 */
export type EventStormingCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the EventStorming
   */
  select?: Prisma.EventStormingSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the EventStorming
   */
  omit?: Prisma.EventStormingOmit<ExtArgs> | null;
  /**
   * The data used to create many EventStormings.
   */
  data: Prisma.EventStormingCreateManyInput | Prisma.EventStormingCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventStormingIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * EventStorming update
 */
export type EventStormingUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the EventStorming
   */
  select?: Prisma.EventStormingSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the EventStorming
   */
  omit?: Prisma.EventStormingOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventStormingInclude<ExtArgs> | null;
  /**
   * The data needed to update a EventStorming.
   */
  data: Prisma.XOR<Prisma.EventStormingUpdateInput, Prisma.EventStormingUncheckedUpdateInput>;
  /**
   * Choose, which EventStorming to update.
   */
  where: Prisma.EventStormingWhereUniqueInput;
};

/**
 * EventStorming updateMany
 */
export type EventStormingUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update EventStormings.
   */
  data: Prisma.XOR<
    Prisma.EventStormingUpdateManyMutationInput,
    Prisma.EventStormingUncheckedUpdateManyInput
  >;
  /**
   * Filter which EventStormings to update
   */
  where?: Prisma.EventStormingWhereInput;
  /**
   * Limit how many EventStormings to update.
   */
  limit?: number;
};

/**
 * EventStorming updateManyAndReturn
 */
export type EventStormingUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the EventStorming
   */
  select?: Prisma.EventStormingSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the EventStorming
   */
  omit?: Prisma.EventStormingOmit<ExtArgs> | null;
  /**
   * The data used to update EventStormings.
   */
  data: Prisma.XOR<
    Prisma.EventStormingUpdateManyMutationInput,
    Prisma.EventStormingUncheckedUpdateManyInput
  >;
  /**
   * Filter which EventStormings to update
   */
  where?: Prisma.EventStormingWhereInput;
  /**
   * Limit how many EventStormings to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventStormingIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * EventStorming upsert
 */
export type EventStormingUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the EventStorming
   */
  select?: Prisma.EventStormingSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the EventStorming
   */
  omit?: Prisma.EventStormingOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventStormingInclude<ExtArgs> | null;
  /**
   * The filter to search for the EventStorming to update in case it exists.
   */
  where: Prisma.EventStormingWhereUniqueInput;
  /**
   * In case the EventStorming found by the `where` argument doesn't exist, create a new EventStorming with this data.
   */
  create: Prisma.XOR<Prisma.EventStormingCreateInput, Prisma.EventStormingUncheckedCreateInput>;
  /**
   * In case the EventStorming was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EventStormingUpdateInput, Prisma.EventStormingUncheckedUpdateInput>;
};

/**
 * EventStorming delete
 */
export type EventStormingDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the EventStorming
   */
  select?: Prisma.EventStormingSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the EventStorming
   */
  omit?: Prisma.EventStormingOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventStormingInclude<ExtArgs> | null;
  /**
   * Filter which EventStorming to delete.
   */
  where: Prisma.EventStormingWhereUniqueInput;
};

/**
 * EventStorming deleteMany
 */
export type EventStormingDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which EventStormings to delete
   */
  where?: Prisma.EventStormingWhereInput;
  /**
   * Limit how many EventStormings to delete.
   */
  limit?: number;
};

/**
 * EventStorming without action
 */
export type EventStormingDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the EventStorming
   */
  select?: Prisma.EventStormingSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the EventStorming
   */
  omit?: Prisma.EventStormingOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventStormingInclude<ExtArgs> | null;
};
