name: CI
on:
  pull_request:
  push:
    branches:
      - main

env:
  DO_NOT_TRACK: 1
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  ci:
    name: CI
    timeout-minutes: 15
    runs-on: ubuntu-latest
    outputs:
      event-storming-ui: ${{ steps.affected.outputs.event-storming-ui }}
      event-storming-api: ${{ steps.affected.outputs.event-storming-api }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize dprint cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/dprint
          key: dprint-${{ hashFiles('dprint.json') }}

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: CI
        run: pnpm exec turbo run ci --affected
