name: CI
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  DO_NOT_TRACK: 1
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  ci:
    name: CI
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: CI
        run: pnpm run ci

  deploy-event-storming-ui:
    name: Deploy event storming ui
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: eu-west-3

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build & push event storming ui container
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/ddd-lab/event-storming/ui:${{ github.sha }} \
            -f event-storming/ui/Dockerfile \
            --secret id=turbo_team,env=TURBO_TEAM \
            --secret id=turbo_token,env=TURBO_TOKEN .
          docker push ${{ steps.login-ecr.outputs.registry }}/ddd-lab/event-storming/ui:${{ github.sha }}

  deploy-event-storming-api:
    name: Deploy event storming api
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: eu-west-3

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build & push event storming api container
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/ddd-lab/event-storming/api:${{ github.sha }} \
            -f event-storming/api/Dockerfile \
            --secret id=turbo_team,env=TURBO_TEAM \
            --secret id=turbo_token,env=TURBO_TOKEN .
          docker push ${{ steps.login-ecr.outputs.registry }}/ddd-lab/event-storming/api:${{ github.sha }}
